apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-release
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: platform-demonstration
data:
  chartVersion: {{ .Chart.Version | quote }}
  slot: {{ .Values.slot | quote }}
  purpose: {{ .Values.purpose | quote }}
