trigger: none
pr: none
parameters:
  - name: targetClusters
    type: object
    default: [aks01]
  - name: deploySequentially
    type: boolean
    default: true
resources:
  repositories:
    - repository: aksTemplates
      type: git
      name: ExampleProject/aks-delivery-templates
      ref: 'd15f578dd05d1becf162b5fa67b5d0503a06da4c'
stages:
  - template: azure-pipelines/stages/platform-services.yml@aksTemplates
    parameters:
      serviceConnection: example-platform-oidc
      environment: pprd
      region: uks
      targetClusters: ${{ parameters.targetClusters }}
      deploySequentially: ${{ parameters.deploySequentially }}
      configFile: platform.services.json
      pool: {name: aks-private}
