name: Platform services
on:
  workflow_dispatch:
    inputs:
      target-clusters:
        type: choice
        options: ['["aks01"]', '["aks02"]', '["aks01","aks02"]']
        default: '["aks01"]'
      deploy-sequentially:
        type: boolean
        default: true
permissions: {contents: read, id-token: write}
jobs:
  platform:
    uses: MikeeeGit/aks-delivery-templates/.github/workflows/platform-services.yml@d15f578dd05d1becf162b5fa67b5d0503a06da4c
    with:
      template-ref: 'd15f578dd05d1becf162b5fa67b5d0503a06da4c'
      config: platform.services.json
      environment: pprd
      region: uks
      target-clusters: ${{ inputs.target-clusters }}
      deploy-sequentially: ${{ inputs.deploy-sequentially }}
      client-id: ${{ vars.PLATFORM_CLIENT_ID }}
      runs-on: '["self-hosted","linux","aks-private"]'
